corrected aws account get logic

diff --git a/.github/workflows/terraform-apply.yaml b/.github/workflows/terraform-apply.yaml
--- a/.github/workflows/terraform-apply.yaml
+++ b/.github/workflows/terraform-apply.yaml
@@ -29,22 +29,23 @@ jobs:
                 role-to-assume: arn:aws:iam::${{ secrets.admin_account_id }}:role/${{ secrets.role_name }}
                 aws-region: us-east-1
             
-            - name: Set Accout ID
-              id : set_account_id
+            - name: Set Account ID
+              id: set_account_id
               shell: bash
               run: |
-               if ['${{ inputs.environment }}' -eq 'dev']; then
-                AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Dev")
-                echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
-               elif ['${{ inputs.environment }}' -eq 'uat']; then
-                AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Uat")
-                echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
-               elif ['${{ inputs.environment }}' -eq 'prod']; then
-                AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Prod")
-                echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
-               else 
-                echo "Unable to establish account id!"
-                exit 1
+                if [[ '${{ inputs.environment }}' == 'dev' ]]; then
+                  AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Dev")
+                  echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
+                elif [[ '${{ inputs.environment }}' == 'uat' ]]; then
+                  AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Uat")
+                  echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
+                elif [[ '${{ inputs.environment }}' == 'prod' ]]; then
+                  AWS_ACCOUNT_ID=$(aws ssm get-parameter --name "The-Wild-West-AccountID-Prod")
+                  echo "aws_account_id=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
+                else
+                  echo "Unable to establish account id!"
+                  exit 1
+                fi
 
             - name: AWS Login - Application Environment
               uses: aws-actions/configure-aws-credentials@v4
